name: Procesar y Actualizar Grafo

on:
  push:
    branches: [ main ]
  issues:
    types: [opened, edited]

jobs:
  update-graph:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt

    - name: Generar grafo
      env:
        GITHUB_USER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -c "from utils.graph_generator import generate_graph; generate_graph()"

    - name: Commit y Push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add docs/index.html
        git commit -m "Actualizar grafo"
        git push