name: Procesar y Actualizar Grafo

on:
  push:
    branches: [ main ]
  issues:
    types: [opened, edited]

jobs:
  update-graph:
    runs-on: ubuntu-latest
    permissions:   # ¡Añade esto!
      contents: write
      issues: write
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Necesario para hacer push
        token: ${{ secrets.GITHUB_TOKEN }}  # ¡Añade esto!

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt

    - name: Generar grafo
      env:
        GITHUB_USER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -c "from utils.graph_generator import generate_graph; generate_graph()"

    - name: Commit y Push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git checkout main  # Asegura que estás en la rama correcta
        git add docs/index.html
        git commit -m "Actualizar grafo"
        git push origin main